### PR TITLE
Move to SDP pipeline

### PR DESCRIPTION
**Pull request by TianqiZhang**

### CODE REVIEW

**Comment by mimisasouvanh** [comment]
@v-alje Can you merge this PR? The validation warnings are by design. If you need diff reports, please let me know. 
cc @TianqiZhang

**Comment by mairaw** [comment]
Can you send us the diff report @mimisasouvanh? @scottaddie

**Comment by TianqiZhang** [comment]
@mairaw @mimisasouvanh here's the diff report:
[aspnet-apidocs-2019-11-12-01-00-09.xlsx](https://github.com/aspnet/ApiDocs/files/3834480/aspnet-apidocs-2019-11-12-01-00-09.xlsx)

**Comment by mairaw** [comment]
Rebuilding to get a build report. Old one wasn't working anymore.

**Comment by mairaw** [comment]
@TianqiZhang this branch was severely outdated causing the diff report to contain APIs that are no longer in this repo. Can you regenerate a new diff report? Thanks.

**Pull request merged**
