### PR TITLE
Limit search to API docs

### PR DESCRIPTION
**Pull request by Rick-Anderson**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@tdykstra  I opened an issue on this - my code change breaks the build.

**Comment by tdykstra** [comment]
@Rick-Anderson I approved this before I saw all the errors - could the format of the searchScope entry be incorrect?

**Comment by Rick-Anderson** [comment]
@tdykstra  It's a copy/paste from the Core version. I'll let the help desk figure it out.

**Comment by Rick-Anderson** [comment]
PR #16 does this.

**Pull request closed without merging**
