### PR TITLE
🐲 Add ASP.NET Content

### PR DESCRIPTION
**Pull request by dend**

### CODE REVIEW

**Comment by dend** [comment]
@danroth27 @Rick-Anderson - this PR introduces API documentation for ASP.NET MVC and ASP.NET MVC Web Pages. Please sign-off that it's OK to release these docs here. Once they are out, we will work on redirecting the MSDN content here.

**Comment by danroth27** [comment]
> this PR introduces API documentation for ASP.NET MVC and ASP.NET MVC Web Pages. Please sign-off that it's OK to release these docs here

I assume you mean ASP.NET MVC and ASP.NET ~~MVC~~ Web Pages. Moving the API documentation for these frameworks here is fine with me.

What about ASP.NET Web API or ASP.NET SignalR?

**Comment by Rick-Anderson** [comment]
@dend  ditto on OK to moving API docs off MSDN. Is there anyway to review the built API pages?

**Comment by mairaw** [comment]
@Rick-Anderson @scottaddie is it ok to merge this? I need to push the metadata updates live.

**Comment by Rick-Anderson** [comment]
@mairaw 	go ahead.

**Comment by mairaw** [comment]
Removed the do-not-merge label then @Rick-Anderson 😄

**Pull request merged**
