### PR TITLE
merging master to live

### PR DESCRIPTION
**Pull request by bradygaster**

### CODE REVIEW

**Comment by TianqiZhang** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/aspnet/ApiDocs/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | | [Details](#user-content-.openpublishing.publish.config.json)
[README.md](https://github.com/aspnet/ApiDocs/blob/master/README.md) | :white_check_mark:Succeeded | | [Details](#user-content-README.md)



For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C12%5Cec2d4c11-07c2-8de2-5380-c643a523bb70%5CPullRequest%5C201611120800359597-11%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TianqiZhang** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/aspnet/ApiDocs/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | | [Details](#user-content-.openpublishing.publish.config.json)
[CONTRIBUTING.md](https://github.com/aspnet/ApiDocs/blob/master/CONTRIBUTING.md) | :white_check_mark:Succeeded | | [Details](#user-content-CONTRIBUTING.md)
[README.md](https://github.com/aspnet/ApiDocs/blob/master/README.md) | :white_check_mark:Succeeded | | [Details](#user-content-README.md)




For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C14%5Cec2d4c11-07c2-8de2-5380-c643a523bb70%5CPullRequest%5C201611140855052851-11%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TianqiZhang** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/aspnet/ApiDocs/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | | [Details](#user-content-.openpublishing.publish.config.json)
[CONTRIBUTING.md](https://github.com/aspnet/ApiDocs/blob/master/CONTRIBUTING.md) | :white_check_mark:Succeeded | | [Details](#user-content-CONTRIBUTING.md)
[README.md](https://github.com/aspnet/ApiDocs/blob/master/README.md) | :white_check_mark:Succeeded | | [Details](#user-content-README.md)




For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C14%5Cec2d4c11-07c2-8de2-5380-c643a523bb70%5CPullRequest%5C201611142132179222-11%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Anderson** [comment]
@bradygaster  what do you want to do with this PR?

**Pull request merged**
