### PR TITLE
ASP.NET Core API Reference adding descriptions

### PR DESCRIPTION
**Pull request by merrua**
On the ASP.NET Core API Reference page, I've added a description to the namespaces that do not have them.

### CODE REVIEW

**Comment by guardrex** [comment]
Fixes #2197

cc/ @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@guardrex  what are all those extra commits and that warning all about?

**Comment by guardrex** [comment]
Not sure ... I didn't know that 2197 was already done ... it was (hiding) over here in this repo. After I discovered this, I closed the one I did.

**Comment by Rick-Anderson** [comment]
@danroth27  I assume our readme for this repo is still correct.

API PR's ( api/autoapi/... ) should not be made here. Changes to API documentation should be made in the source repository against the triple slash /// comments.

cc @merrua

**Comment by Rick-Anderson** [comment]
@merrua  thanks for your contribution. We're trying to figure out the best way to fix this.

**Comment by Rick-Anderson** [comment]
@merrua  you can make these changes at https://github.com/aspnet/ApiDocs/tree/master/api/xml

**Make the changes on  the Summary node.**
Or I can make the changes if you like.

cc @dend @danroth27

**Comment by merrua** [comment]
@Rick-Anderson Could you point me to where the Summary node is? I don't see a summary node on that page. 

Clicking into cookie policy for example, brings me to https://github.com/aspnet/ApiDocs/tree/master/api/xml/Microsoft.AspNetCore.CookiePolicy
It does not have a summary node file and does not seem to match the wiki page I looked at that was missing information? 

I originally edited this through the wiki link, and it doesn't seem obvious where to make the change through that link.

I'd like to make the change in order to learn.

**Comment by Rick-Anderson** [comment]
@merrua  take a look at https://github.com/aspnet/ApiDocs/pull/30

**Comment by Rick-Anderson** [comment]
@merrua  this file you want is https://github.com/aspnet/ApiDocs/blob/master/api/xml/Microsoft.AspNetCore.CookiePolicy/CookiePolicyMiddleware.xml  
at least I think. Dend will let us know.

**Comment by danroth27** [comment]
To provide  namespace descriptions we need to update Summary node in the the ns-* files under https://github.com/aspnet/ApiDocs/tree/master/api/xml.

**Pull request closed without merging**
